name: Build Yukigram for Windows x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: yukigram/yukigram
        ref: dev
        submodules: recursive

    # Set up Visual Studio 2022
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'  # Visual Studio 2022

    # Install CMake
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2.0.2
      with:
        cmake-version: '3.28'  # Use a version compatible with Yukigram (3.21+)

    # Install vcpkg and dependencies
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install
        .\vcpkg\vcpkg install --triplet x64-windows
      shell: cmd
      working-directory: ${{ github.workspace }}

    # Configure CMake
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: cmd

    # Build the project
    - name: Build Yukigram
      run: |
        cd build
        cmake --build . --config Release
      shell: cmd

    # Upload the built executable as an artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yukigram-executable
        path: ${{ github.workspace }}/build/Release/yukigram.exe
